### ISSUE TITLE
LiquidCrystal_I2C

### ISSUE THREAD

**Issue by R4DH2N** [zrox/gro-matic#4]
LiquidCrystal_I2C lcd(LED_ADDR, 2, 1, 0, 4, 5, 6, 7, BACKLIGHT_PIN, POSITIVE);

Ist nicht Kompelierbar! Die (Constante) variable "POSITIVE" exestiert nicht... lcd(); hat nur drei argumente als Prototype...

habe es in meinen Code geändert und zu lcd(LED_ADDR, 20, 4); und im setup zu lcd.begin() "lcd.begin() nimmt überhaupt keine argumente..."

Jetz Kompeliert der Code zu 100% fehlerfrei! 

verstehe nicht wie das vorher überhaupt funktionieren konnte??

Ich bitte um aufklärung was du dir dabei gedacht hast, evt verwende ich die falsche lib odert sonst was...

Der Code ist in meinen Fork im "trunk"  zweig der müsste mal von jemanden getestet werden weil ich die Hardware nicht habe...

**Comment by zrox** [comment]
Hi, morgen bin ich wieder zuhause :-)

Du hast die falsche Lib verwendet schau mal im thread habe ich mal die libs hochgeladen oder such mal nach der newLiquidcrystal damit klappt es so wie ich es ursprünglich zusammengebastelt hatte. Viele Grüße zrox
